/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common.component;

import com.artemis.*;

public class ErrorComp extends Component {
	public static enum ErrorCode {
		ALREADY_LOGGED, INVALID_LOGIN, INVALID_STATE, NAME_ALREADY_USED, INVALID_UUID, UNKNOWN_ERROR
	};

	public static final ErrorComp ALREADY_LOGGED = new ErrorComp(ErrorCode.ALREADY_LOGGED);
	public static final ErrorComp INVALID_LOGIN = new ErrorComp(ErrorCode.INVALID_LOGIN);
	public static final ErrorComp INVALID_STATE = new ErrorComp(ErrorCode.INVALID_STATE);
	public static final ErrorComp INVALID_UUID = new ErrorComp(ErrorCode.INVALID_UUID);
	public static final ErrorComp NAME_ALREADY_USED = new ErrorComp(ErrorCode.NAME_ALREADY_USED);
	public static final ErrorComp UNKNOWN_ERROR = new ErrorComp(ErrorCode.UNKNOWN_ERROR);

	public ErrorCode code;

	public ErrorComp() {
	}

	private ErrorComp(ErrorCode code) {
		this.code = code;
	}

	@Override
	public String toString() {
		return "ErrorComp [code=" + code + "]";
	}
}
