/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common.pojo;

public class Point {
	public float x;
	public float y;

	/**
	 * Default constructor.
	 */
	public Point() {
	}

	/**
	 * All-args constructor.
	 */
	public Point(java.lang.Float x, java.lang.Float y) {
		this.x = x;
		this.y = y;
	}
}
