/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;
import unknow.kyhtanil.common.pojo.*;

import com.artemis.*;

public class Attack extends PooledComponent
	{
	public UUID uuid;
	public int id;
	public Object target;

	/**
	 * Default constructor. 
	 */
	public Attack()
		{
		}

	/**
	 * All-args constructor.
	 */
	public Attack(UUID uuid, java.lang.Integer id, java.lang.Object target)
		{
		this.uuid=uuid;
		this.id=id;
		this.target=target;
		}

	protected void reset()
		{
		}

	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
