/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;
import unknow.kyhtanil.common.pojo.*;

import com.artemis.*;

public class DamageReport extends PooledComponent
	{
	public UUID uuid;
	public int damage;

	/**
	 * Default constructor.
	 */
	public DamageReport()
		{
		}

	/**
	 * All-args constructor.
	 */
	public DamageReport(UUID uuid, java.lang.Integer damage)
		{
		this.uuid=uuid;
		this.damage=damage;
		}

	protected void reset()
		{
		}
	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
