/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;
import unknow.kyhtanil.common.pojo.*;

import com.artemis.*;

public class Despawn extends PooledComponent
	{
	public UUID uuid;

	/**
	 * Default constructor.
	 */
	public Despawn()
		{
		}

	/**
	 * All-args constructor.
	 */
	public Despawn(UUID uuid)
		{
		this.uuid=uuid;
		}

	protected void reset()
		{
		}
	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
