/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;
import unknow.kyhtanil.common.pojo.*;

import com.artemis.*;

public class LogChar extends PooledComponent
	{
	public UUID uuid;
	public int character;

	/**
	 * Default constructor. 
	 */
	public LogChar()
		{
		}

	/**
	 * All-args constructor.
	 */
	public LogChar(UUID uuid, int character)
		{
		this.uuid=uuid;
		this.character=character;
		}

	protected void reset()
		{
		}

	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
