/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;

import com.artemis.*;

public class Login extends PooledComponent
	{
	public String login;
	public String pass;

	/**
	 * Default constructor.
	 */
	public Login()
		{
		}

	/**
	 * All-args constructor.
	 */
	public Login(String login, String pass)
		{
		this.login=login;
		this.pass=pass;
		}

	protected void reset()
		{
		}
	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
