/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import java.util.*;

import com.artemis.*;

public class LogResult extends PooledComponent
	{
	public UUID uuid;
	public List<CharDesc> characters;

	/**
	 * Default constructor.
	 */
	public LogResult()
		{
		}

	/**
	 * All-args constructor.
	 */
	public LogResult(UUID uuid, List<CharDesc> characters)
		{
		this.uuid=uuid;
		this.characters=characters;
		}

	protected void reset()
		{
		}
	}
