/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;
import unknow.kyhtanil.common.pojo.*;

import com.artemis.*;

public class LogResult extends PooledComponent
	{
	public UUID uuid;
	public CharDesc[] characters;

	/**
	 * Default constructor.
	 */
	public LogResult()
		{
		}

	/**
	 * All-args constructor.
	 */
	public LogResult(UUID uuid, CharDesc[] characters)
		{
		this.uuid=uuid;
		this.characters=characters;
		}

	protected void reset()
		{
		}
	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
