/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import com.artemis.*;

public class Move extends PooledComponent
	{
	public UUID uuid;
	public float x;
	public float y;
	public float dirX;
	public float dirY;

	/**
	 * Default constructor.
	 */
	public Move()
		{
		}

	/**
	 * All-args constructor.
	 */
	public Move(UUID uuid, java.lang.Float x, java.lang.Float y, java.lang.Float dirX, java.lang.Float dirY)
		{
		this.uuid=uuid;
		this.x=x;
		this.y=y;
		this.dirX=dirX;
		this.dirY=dirY;
		}

	protected void reset()
		{
		}
	}
