/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;
import unknow.kyhtanil.common.pojo.*;

import com.artemis.*;

public class Move extends PooledComponent
	{
	public UUID uuid;
	public float x;
	public float y;
	public float direction;

	/**
	 * Default constructor.
	 */
	public Move()
		{
		}

	/**
	 * All-args constructor.
	 */
	public Move(UUID uuid, float x, float y, float direction)
		{
		this.uuid=uuid;
		this.x=x;
		this.y=y;
		this.direction=direction;
		}

	protected void reset()
		{
		}

	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
