/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;
import unknow.kyhtanil.common.component.*;

import com.artemis.*;

public class PjInfo extends PooledComponent
	{
	public String name;
	public int map;
	public float x;
	public float y;
	public int hp;
	public int mp;

	public Body body;
	public CalculatedComp total;

	/**
	 * Default constructor.
	 */
	public PjInfo()
		{
		}

	/**
	 * All-args constructor.
	 */
	public PjInfo(String name, int map, float x, float y, int hp, int mp, Body body, CalculatedComp total)
		{
		this.name=name;
		this.map=map;
		this.x=x;
		this.y=y;
		this.hp=hp;
		this.mp=mp;
		this.body=body;
		this.total=total;
		}

	protected void reset()
		{
		}
	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
