/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import com.artemis.*;

public class PjInfo extends PooledComponent
	{
	public String name;
	public int level;
	public int map;
	public float x;
	public float y;
	public int hp;
	public int mp;
	public int constitution;
	public int strength;
	public int concentration;
	public int intelligence;
	public int dexterity;

	/**
	 * Default constructor.
	 */
	public PjInfo()
		{
		}

	/**
	 * All-args constructor.
	 */
	public PjInfo(String name, int level, int map, float x, float y, int hp, int mp, int constitution, int strength, int concentration, int intelligence, int dexterity)
		{
		this.name=name;
		this.level=level;
		this.map=map;
		this.x=x;
		this.y=y;
		this.hp=hp;
		this.mp=mp;
		this.constitution=constitution;
		this.strength=strength;
		this.concentration=concentration;
		this.intelligence=intelligence;
		this.dexterity=dexterity;
		}

	protected void reset()
		{
		}
	}
