/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import com.artemis.*;

public class Spawn extends PooledComponent
	{
	public UUID uuid;
	public int type;
	public String name;
	public int hp;
	public float x;
	public float y;
	public float dirX;
	public float dirY;

	/**
	 * Default constructor.  
	 */
	public Spawn()
		{
		}

	/**
	 * All-args constructor.
	 */
	public Spawn(UUID uuid, java.lang.Integer type, java.lang.String name, java.lang.Integer hp, java.lang.Float x, java.lang.Float y, java.lang.Float dirX, java.lang.Float dirY)
		{
		this.uuid=uuid;
		this.type=type;
		this.name=name;
		this.hp=hp;
		this.x=x;
		this.y=y;
		this.dirX=dirX;
		this.dirY=dirY;
		}

	protected void reset()
		{
		}
	}
