/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import unknow.common.tools.*;
import unknow.kyhtanil.common.component.*;
import unknow.kyhtanil.common.pojo.*;

import com.artemis.*;

public class Spawn extends PooledComponent
	{
	public UUID uuid;
	public int type;
	public String name;
	public CalculatedComp total;
	public float x;
	public float y;
	public float direction;

	/**
	 * Default constructor.  
	 */
	public Spawn()
		{
		}

	/**
	 * All-args constructor.
	 */
	public Spawn(UUID uuid, int type, String name, CalculatedComp total, float x, float y, float direction)
		{
		this.uuid=uuid;
		this.type=type;
		this.name=name;
		this.total=total;
		this.x=x;
		this.y=y;
		this.direction=direction;
		}

	protected void reset()
		{
		}

	public String toString()
		{
		return JsonUtils.toString(this);
		}
	}
