/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package unknow.kyhtanil.common;

import java.util.*;

public class UUID
	{
	public byte[] bytes;

	/** Creates a new UUID */
	public UUID()
		{
		}

	/**
	 * Creates a new UUID with the given bytes.
	 * @param bytes The bytes to create the new UUID. 
	 */
	public UUID(byte[] bytes)
		{
		this.bytes=bytes;
		}

	@Override
	public int hashCode()
		{
		return Arrays.hashCode(bytes);
		}

	public boolean equals(Object obj)
		{
		if(obj==this)
			return true;
		if(obj instanceof UUID)
			return Arrays.equals(bytes, ((UUID)obj).bytes);
		if(obj instanceof byte[])
			return Arrays.equals(bytes, (byte[])obj);
		return false;
		}

	@Override
	public String toString()
		{
		return Arrays.toString(bytes);
		}
	}